/**
 * Pre-populates the Level 2 (Vercel Blob) dependency cache so the first user
 * to open a popular starter gets a CDN hit instead of paying the cold npm
 * cost. Without this, whoever opens a template first eats the full install —
 * measured at 276s for nextjs on a fast host connection, considerably worse
 * inside the WASM sandbox — and every user pays it again if that one unlucky
 * install fails to upload for any reason.
 *
 * Usage:
 *   npx tsx scripts/warm-blob-cache.ts                 # all templates in POPULAR_TEMPLATES
 *   npx tsx scripts/warm-blob-cache.ts nextjs react-ts # just these
 *   npx tsx scripts/warm-blob-cache.ts --force         # overwrite entries that are still fresh
 *   npx tsx scripts/warm-blob-cache.ts --dry-run       # build bundles, print keys, upload nothing
 *
 * Requires BLOB_READ_WRITE_TOKEN in the environment (.env is loaded below).
 *
 * NOTE ON THE WRITE PATH: this uploads with the server-side @vercel/blob put(),
 * which does NOT go through app/api/dependency-cache/blob-upload and therefore
 * bypasses that route's freshness write-gate. That's intentional for an
 * operator-run script — it's how a deliberate refresh is possible at all — but
 * it does mean this script can clobber a live entry, hence --force being
 * opt-in rather than the default.
 */
import "dotenv/config";
import { execFileSync } from "child_process";
import { createHash } from "crypto";
import { gzipSync } from "zlib";
import {
  readFileSync,
  readdirSync,
  mkdtempSync,
  writeFileSync,
  rmSync,
  existsSync,
} from "fs";
import { join, resolve } from "path";
import { tmpdir } from "os";

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

/**
 * Starters worth pre-warming. Ordered roughly by how heavy their install is —
 * the expensive ones are exactly the ones where a cold cache hurts most.
 */
const POPULAR_TEMPLATES = [
  "nextjs",
  "nextjs-shadcn",
  "react-ts",
  "react",
  "vue",
  "sveltekit",
  "astro-shadcn",
  "vite-shadcn",
  "angular",
];

const STARTERS_DIR = resolve(process.cwd(), "vibecode-starters");

/** Mirrors MAX_AGE_MS in lib/dependency-cache-ttl.ts. */
const MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;

/** Mirrors the route's maximumSizeInBytes. */
const MAX_UPLOAD_BYTES = 300 * 1024 * 1024;

/**
 * WebContainer reports itself as linux/x64. npm gates optionalDependencies on
 * platform, so installing on a Windows or macOS host without these overrides
 * produces a tree containing that host's native binaries and MISSING the ones
 * the sandbox actually needs — e.g. @next/swc-win32-x64-msvc instead of
 * @next/swc-linux-x64-gnu. That bundle would restore "successfully" and then
 * fail at dev-server start, which is a far worse outcome than a cache miss.
 */
const TARGET_OS = "linux";
const TARGET_CPU = "x64";

// ---------------------------------------------------------------------------
// Bundle format — must byte-for-byte match
// modules/webcontainers/lib/node-modules-persistence.ts
// ---------------------------------------------------------------------------

interface BundleEntry {
  path: string;
  isDir: boolean;
  size: number;
}

/**
 * Same key derivation as computeDependencyCacheKey() in
 * node-modules-persistence.ts. If these two ever disagree the cache silently
 * stops working: this script writes keys nothing reads, and every user falls
 * through to npm while the Blob store quietly fills with orphans. Any change
 * here needs the same change there.
 */
function dependencyCacheKey(packageJson: string, packageLock: string | null): string {
  const input = packageLock
    ? `${packageJson}\n--devpilot-lock--\n${packageLock}`
    : packageJson;
  return createHash("sha256").update(input, "utf8").digest("hex");
}

function blobPathname(pkgHash: string): string {
  return `node-modules/${pkgHash}.bin`;
}

function encodeBundleForBlob(
  entries: BundleEntry[],
  compressedData: Buffer,
  rawSize: number,
  cachedAt: number
): Buffer {
  const header = Buffer.from(
    JSON.stringify({ entries, compressed: true, rawSize, cachedAt }),
    "utf8"
  );
  const len = Buffer.alloc(4);
  len.writeUInt32LE(header.byteLength, 0);
  return Buffer.concat([len, header, compressedData]);
}

// ---------------------------------------------------------------------------
// Tree walking
// ---------------------------------------------------------------------------

/**
 * Walks node_modules the same way the browser capture does: files in traversal
 * order, empty directories recorded explicitly, symlinks skipped entirely.
 *
 * .bin is skipped wholesale rather than filtered entry-by-entry. In the
 * container its contents are symlinks (unrepresentable in this format, and
 * regenerated by regenerateBinLinks after every restore); on a Windows host
 * npm writes .cmd/.ps1 shims there instead, which are real files that would
 * otherwise get captured and shipped into a Linux sandbox as dead weight.
 */
function walkNodeModules(root: string): { files: string[]; emptyDirs: string[] } {
  const files: string[] = [];
  const emptyDirs: string[] = [];

  function recurse(dir: string, base: string): void {
    let items;
    try {
      items = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }

    if (items.length === 0) {
      if (base) emptyDirs.push(base);
      return;
    }

    for (const item of items) {
      if (item.isSymbolicLink()) continue;

      const rel = base ? `${base}/${item.name}` : item.name;
      const full = join(dir, item.name);

      if (item.isDirectory()) {
        if (item.name === ".bin") continue;
        recurse(full, rel);
      } else if (item.isFile()) {
        files.push(rel);
      }
    }
  }

  recurse(root, "");
  return { files, emptyDirs };
}

function buildBundle(nodeModulesPath: string): {
  entries: BundleEntry[];
  compressedData: Buffer;
  rawSize: number;
} {
  const { files, emptyDirs } = walkNodeModules(nodeModulesPath);

  const entries: BundleEntry[] = emptyDirs.map((path) => ({ path, isDir: true, size: 0 }));
  const chunks: Buffer[] = [];
  let rawSize = 0;

  for (const rel of files) {
    let data: Buffer;
    try {
      data = readFileSync(join(nodeModulesPath, rel));
    } catch {
      continue;
    }
    entries.push({ path: rel, isDir: false, size: data.byteLength });
    chunks.push(data);
    rawSize += data.byteLength;
  }

  // Node-side this is a plain in-process concat rather than the browser's
  // streaming pipeline: this runs on an operator machine with a normal heap,
  // not a tab, so the ~280MB peak that forced streaming in the browser is a
  // non-issue here. gzip level 6 matches CompressionStream's default so warm
  // and cold entries stay comparably sized.
  const raw = Buffer.concat(chunks, rawSize);
  const compressedData = gzipSync(raw, { level: 6 });

  return { entries, compressedData, rawSize };
}

// ---------------------------------------------------------------------------
// Blob I/O
// ---------------------------------------------------------------------------

async function existingEntryAge(pathname: string): Promise<number | null> {
  const base = process.env.NEXT_PUBLIC_BLOB_BASE_URL;
  if (!base) return null;

  try {
    const res = await fetch(`${base}/${pathname}`, { headers: { Range: "bytes=0-3" } });
    if (res.status === 404) return null;
    if (res.status !== 200 && res.status !== 206) return null;

    const lenBytes = Buffer.from(await res.arrayBuffer());
    if (lenBytes.byteLength < 4) return null;
    const headerLen = lenBytes.readUInt32LE(0);
    if (headerLen <= 0 || headerLen > 20 * 1024 * 1024) return null;

    // Range reads can come back short against a freshly-written object — ask
    // for the remainder instead of reporting the entry as unreadable, which
    // would silently turn a --force-less run into an unnecessary re-upload.
    const chunks: Buffer[] = [];
    let received = 0;
    for (let attempt = 0; attempt < 5 && received < headerLen; attempt++) {
      const headerRes = await fetch(`${base}/${pathname}`, {
        headers: { Range: `bytes=${4 + received}-${3 + headerLen}` },
      });
      if (headerRes.status !== 200 && headerRes.status !== 206) return null;
      const chunk = Buffer.from(await headerRes.arrayBuffer());
      if (chunk.byteLength === 0) break;
      chunks.push(chunk);
      received += chunk.byteLength;
    }
    if (received < headerLen) return null;

    const header = JSON.parse(Buffer.concat(chunks).subarray(0, headerLen).toString("utf8"));
    if (typeof header.cachedAt !== "number") return null;
    return Date.now() - header.cachedAt;
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Per-template pipeline
// ---------------------------------------------------------------------------

interface WarmResult {
  template: string;
  status: "uploaded" | "skipped-fresh" | "skipped-too-large" | "failed" | "dry-run";
  pkgHash?: string;
  bytes?: number;
  files?: number;
  durationMs?: number;
  reason?: string;
}

async function warmTemplate(
  template: string,
  opts: { force: boolean; dryRun: boolean }
): Promise<WarmResult> {
  const started = Date.now();
  const templateDir = join(STARTERS_DIR, template);

  const pkgPath = join(templateDir, "package.json");
  if (!existsSync(pkgPath)) {
    return { template, status: "failed", reason: `no package.json at ${pkgPath}` };
  }

  // Read exactly as path-to-json.ts does (utf8 text), so the hash matches what
  // the browser derives from the same template.
  const packageJson = readFileSync(pkgPath, "utf8");
  const lockPath = join(templateDir, "package-lock.json");
  const packageLock = existsSync(lockPath) ? readFileSync(lockPath, "utf8") : null;

  if (!packageLock) {
    console.warn(
      `  ! ${template} has no package-lock.json — its key falls back to package.json only, ` +
        `so the entry is only as trustworthy as the 7-day TTL.`
    );
  }

  const pkgHash = dependencyCacheKey(packageJson, packageLock);
  const pathname = blobPathname(pkgHash);

  if (!opts.force) {
    const age = await existingEntryAge(pathname);
    if (age !== null && age < MAX_AGE_MS) {
      return {
        template,
        status: "skipped-fresh",
        pkgHash,
        reason: `existing entry is ${(age / 3_600_000).toFixed(1)}h old (< 7d)`,
      };
    }
  }

  const workDir = mkdtempSync(join(tmpdir(), `devpilot-warm-${template}-`));

  try {
    writeFileSync(join(workDir, "package.json"), packageJson);
    if (packageLock) writeFileSync(join(workDir, "package-lock.json"), packageLock);

    console.log(`  installing (${TARGET_OS}/${TARGET_CPU})...`);
    execFileSync(
      "npm",
      [
        "install",
        "--no-audit",
        "--no-fund",
        "--ignore-scripts",
        `--os=${TARGET_OS}`,
        `--cpu=${TARGET_CPU}`,
        "--loglevel=error",
      ],
      { cwd: workDir, stdio: "inherit", shell: process.platform === "win32" }
    );

    const nodeModules = join(workDir, "node_modules");
    if (!existsSync(nodeModules)) {
      return { template, status: "failed", reason: "npm install produced no node_modules" };
    }

    console.log(`  packaging...`);
    const { entries, compressedData, rawSize } = buildBundle(nodeModules);
    const payload = encodeBundleForBlob(entries, compressedData, rawSize, Date.now());

    const fileCount = entries.filter((e) => !e.isDir).length;

    if (payload.byteLength > MAX_UPLOAD_BYTES) {
      return {
        template,
        status: "skipped-too-large",
        pkgHash,
        bytes: payload.byteLength,
        files: fileCount,
        reason: `${(payload.byteLength / 1024 / 1024).toFixed(1)}MB exceeds the 300MB route limit`,
      };
    }

    if (opts.dryRun) {
      return {
        template,
        status: "dry-run",
        pkgHash,
        bytes: payload.byteLength,
        files: fileCount,
        durationMs: Date.now() - started,
      };
    }

    console.log(`  uploading ${(payload.byteLength / 1024 / 1024).toFixed(1)}MB...`);
    const { put } = await import("@vercel/blob");
    await put(pathname, payload, {
      access: "public",
      contentType: "application/octet-stream",
      addRandomSuffix: false,
      allowOverwrite: true,
      token: process.env.BLOB_READ_WRITE_TOKEN,
    });

    return {
      template,
      status: "uploaded",
      pkgHash,
      bytes: payload.byteLength,
      files: fileCount,
      durationMs: Date.now() - started,
    };
  } catch (err) {
    return {
      template,
      status: "failed",
      pkgHash,
      reason: err instanceof Error ? err.message : String(err),
    };
  } finally {
    try {
      rmSync(workDir, { recursive: true, force: true });
    } catch {
      console.warn(`  ! could not remove temp dir ${workDir}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const force = args.includes("--force");
  const dryRun = args.includes("--dry-run");
  const named = args.filter((a) => !a.startsWith("--"));
  const templates = named.length > 0 ? named : POPULAR_TEMPLATES;

  if (!dryRun && !process.env.BLOB_READ_WRITE_TOKEN) {
    console.error("BLOB_READ_WRITE_TOKEN is not set — nothing can be uploaded. Aborting.");
    process.exit(1);
  }

  console.log(
    `Warming Blob dependency cache for ${templates.length} template(s)` +
      `${dryRun ? " (dry run)" : ""}${force ? " (force)" : ""}\n`
  );

  const results: WarmResult[] = [];

  for (const template of templates) {
    console.log(`> ${template}`);
    const result = await warmTemplate(template, { force, dryRun });
    results.push(result);

    const detail =
      result.status === "uploaded" || result.status === "dry-run"
        ? `${result.files} files, ${(result.bytes! / 1024 / 1024).toFixed(1)}MB, ${(
            result.durationMs! / 1000
          ).toFixed(0)}s`
        : (result.reason ?? "");
    console.log(`  ${result.status}${detail ? ` — ${detail}` : ""}`);
    if (result.pkgHash) console.log(`  key: ${blobPathname(result.pkgHash)}\n`);
    else console.log("");
  }

  console.log("\nSummary");
  console.log("-------");
  for (const r of results) {
    console.log(`${r.status.padEnd(18)} ${r.template}`);
  }

  const failed = results.filter((r) => r.status === "failed");
  if (failed.length > 0) {
    console.error(`\n${failed.length} template(s) failed.`);
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
